server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: create
          uri: http://localhost:8082
          predicates:
            - Path=/exams/**, 
        - id: request
          uri: http://localhost:8083
          predicates:
            - Path=/examReqs/**, 
        - id: answer
          uri: http://localhost:8084
          predicates:
            - Path=/userAnswereds/**, 
        - id: result
          uri: http://localhost:8085
          predicates:
            - Path=/examResults/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: create
          uri: http://create:8080
          predicates:
            - Path=/exams/**, 
        - id: request
          uri: http://request:8080
          predicates:
            - Path=/examReqs/**, 
        - id: answer
          uri: http://answer:8080
          predicates:
            - Path=/userAnswereds/**, 
        - id: result
          uri: http://result:8080
          predicates:
            - Path=/examResults/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
